"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const authRoutes = (0, express_1.Router)();
authRoutes.post("/register", auth_controller_1.RegisterController);
authRoutes.post("/login", auth_controller_1.loginController);
authRoutes.post("/refresh-token", auth_middleware_1.authMiddleware, auth_controller_1.refreshTokenController);
exports.default = authRoutes;
