"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const transaction_controller_1 = require("../controllers/transaction.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const transactionRoutes = (0, express_1.Router)();
transactionRoutes.post("/scan-receipt", auth_middleware_1.authMiddleware, transaction_controller_1.scanReceiptController);
transactionRoutes.get("/all", auth_middleware_1.authMiddleware, transaction_controller_1.getAllTransactionController);
transactionRoutes.get("/duplicate/:id", auth_middleware_1.authMiddleware, transaction_controller_1.duplicateTransactionController);
transactionRoutes.get("/:id", auth_middleware_1.authMiddleware, transaction_controller_1.getTransactionByIdController);
transactionRoutes.put("/update/:id", auth_middleware_1.authMiddleware, transaction_controller_1.updateTransactionController);
transactionRoutes.post("/create", auth_middleware_1.authMiddleware, transaction_controller_1.createTransactionController);
transactionRoutes.post("/bulk-transaction", auth_middleware_1.authMiddleware, transaction_controller_1.bulkTransactionController);
transactionRoutes.delete("/delete/:id", auth_middleware_1.authMiddleware, transaction_controller_1.deleteTransactionController);
transactionRoutes.delete("/bulk-delete", auth_middleware_1.authMiddleware, transaction_controller_1.bulkDeleteTransactionController);
exports.default = transactionRoutes;
